# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Alphacast"
license = "MIT"
licenselink = "https://github.com/therandomsecurityguy/alphacast/blob/master/LICENSE.md"
description = "A trimmed pocast-theme theme for Hugo"
homepage = "https://github.com/therandomsecurityguy/alphacast"
tags = ["podcast", "responsive"]
features = ["podcast RSS", "subscribe buttons"]
min_version = "0.70.1"
theme_version = "1.0.0"

[author]
  name = "D.C."
  homepage = "https://randomsecurity.dev"
